### ISSUE TITLE
Any updates?

### ISSUE THREAD

**Issue by K0-RR** [LucilleTea/cadmium-fabric#4]
Will this mod be ever updated?

**Comment by LucilleTea** [comment]
seems to still work on 1.17, though at your own risk.
still have no idea how to approach the outstanding issue.
i could update it just to remove the version lock, but due to #1 you can only use it with very few other mods, so it seems a bit pointless.

in all, updates may happen eventually when i feel like digging into things, there's no low hanging fruit worth doing until then.
